---
- hosts: 172.31.33.57
  become: yes
  tasks:
   - name: I want to execute a linux command
     command: hostname -f
     register: myresult

   - name: i'm showing you first task result
     debug:
      msg: "{{myresult}}"
