---
- hosts: 172.31.33.57
  become: yes
  tasks:
   - name: I want to execute a linux command
     command: hostname -f
     register: myresult

   - name: i'm showing you first task result
     debug:
      msg: "{{myresult}}"


   - name: installing git
     apt:
      name: git
      state: present
     when:  myresult.stderr == ""

   - name: installing tree
     apt:
      name: tree
      state: present
     when: myresult.stderr != ""