---
- hosts: 172.31.33.57
  become: yes
  vars:
   myvar1: git
   myvar2: wget

  tasks:

   - name: i want to display myvar1 
     debug:
      msg: "{{myvar1}}"

   - name: installing git
     apt:
      name: "{{myvar1}}"
      state: present

   - name: installing wget
     apt:
      name: "{{myvar2}}"
      state: present