---
- hosts: 172.31.33.57
  become: yes
  tasks:
  - name: installing git
    apt:
     name: git
     state: present

  - name: installing wget
    apt:
      name: wget
      state: presenttt
    ignore_errors: True

  - name: installing tree
    apt:
     name: tree
     state: present