---
- hosts: 172.31.33.57
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
       name: apache2
       state: present
    notify: restartwebserver

  - name: copying file from masterserver to nodeserver
    copy: 
      src: shankar.txt
      dest: /home/shankar/
    notify: restartwebserver
     
  - name: copy indexfile into ansible node side
    copy:
      src: myindex.j2
      dest: /var/www/html/index.html

  - name: downloading jenkins package
    get_url:
      url:  https://get.jenkins.io/war-stable/2.375.1/jenkins.war
      dest: /home/shankar/jenkins.war
      force_basic_auth: yes
    notify: restartwebserver

  handlers:
  - name: restartwebserver
    apt: 
      name: apache2
      state: restarted