---
- hosts: 172.31.33.57
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
       name: apache2
       state: present

  - name: copying file from masterserver to nodeserver
    copy: 
      src: shankar.txt
      dest: /home/shankar/
     
  - name: copy indexfile into ansible node side
    copy:
      src: myindex.j2
      dest: /var/www/html/index.html