---
- hosts: 172.31.33.57
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt: 
       name: apache2
       state: present

  - name: copying file from master to node
    copy: 
      src: shankar.txt
      dest: /home/shankar/
     