---
- hosts: all
  become: yes
  tasks:
  - name: unInstall Apache Web Server
    apt:
        name: apache2
        state: absent
    when: ansible_os_family =="Debian"

  - name: unInstall Apache Web Server

    yum:
        name: httpd
        state: absent
    when: ansible_os_family =="RedHat"

        
