---
- hosts: 172.31.33.57
  become: yes
  vars:
    myvar1: git
    myvar2: wget
    myvar3: tree

  tasks:

  - name: displaying variable of myvar3
    debug:
     msg:'{{myvar3}}'
    ignore_errors: True

  - name: running linux command
    command: hostname -f
    register: myresult
    tags: mylinuxcommand
    ignore_errors: True

  - name: i'm showing my 2nd task result
    debug:
     msg: "{{myresult}}"
    ignore_errors: True

  - name: installing git
    apt: 
      name: "{{myvar1}}"
      state: presentt
    tags: mygit
    when: ansible_os_family== "Debian"
    ignore_errors: True

  - name: installing wget
    apt: 
      name: "{{myvar2}}"
      state: present
    tags: mywget
    when: ansible_os_family== "Debian"
    ignore_errors: True
    
  - name: installing tree
    apt: 
      name: "{{myvar3}}"
      state: present
    tags: mytree
    when: ansible_os_family== "Debiann"
    ignore_errors: True

  - name: installing java11
    apt: 
      name: "{{myjavapackageonubuntu}}"
      state: present
    tags: myjava
    when: ansible_os_family== "Debian"
    ignore_errors: True



       
