---
- hosts: all
  become: yes
  gather_facts: true
  tasks:
  - name: print variable value 
    debug: 
     msg: the value of variable is {{vhost_st}}
    when: vhost_st == 'st1'

  - name: installing git
    apt:
      name: git
      state: present
    when: vhost_st == 'st2'

  