---
- hosts: all
  become: yes
  tasks:
  - name: Install Apache Web Server
    apt:
        name: '{{mywebpackageonubuntu}}'
        state: present
    when: ansible_os_family =="Debian"

  - name: starting Apache Web Server
    service:
        name: '{{mywebpackageonubuntu}}'
        state: started
    when: ansible_os_family =="Debian"

  - name: Install Apache Web Server
    yum:
        name: '{{mywebpackageonredhat}}'
        state: present
    when: ansible_os_family =="RedHat"

  - name: starting Apache Web Server
    service:
        name: '{{mywebpackageonredhat}}'
        state: started
    when: ansible_os_family =="RedHat"

        
